default :
	gcc cache1D.c -Wall -m32 -std=gnu99 -o cache1D
	gcc cache2Drows.c -Wall -m32 -std=gnu99 -o cache2Drows
	gcc cache2Dcols.c -Wall -m32 -std=gnu99 -o cache2Dcols
	gcc cache2Dclash.c -Wall -m32 -std=gnu99 -o cache2Dclash

clean :
	rm -rf cache1D cache2Drows cache2Dcols cache2Dclash
